# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-28 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='text',
            field=models.TextField(default='some thoughts'),
        ),
    ]
